### ISSUE TITLE
Question regarding building samples

### ISSUE THREAD

**Issue by yunchancho** [IntelRealSense/realsense_samples#1]
Hi, 

I would like to run these samples on my ubuntu (16.10) pc with r200.
For building, some dependancies seems to be needed like the followings

librealsense library (https://github.com/IntelRealSense/librealsense)
Intel Linux Realsense SDK library (https://github.com/IntelRealSense/realsense_sdk)
librealsense person tracking library (?)

Is it right?  
But, I didn't find any hint regarding realsense person tracking library.

Thanks in advance.

**Comment by mattcurfman** [comment]
Hi @vinebrancho, please see the corresponding setup script at http://github.intel.com/mcurfman/realsense_scripts/script_beta3_rc3.sh  It will setup the dependencies.  Note that the script is temporary, and will be replaced with more appropriate .deb packages from a realsense apt-get repo.

**Comment by mattcurfman** [comment]
Hi @vinebrancho  we will soon be publishing information regarding how to utilize the sample codes, including dependencies for person tracking.  Anticipate WW03'17 arrival

**Comment by mattcurfman** [comment]
Hi @vinebrancho, please see "Building The Samples" in the README.md @ https://github.com/IntelRealSense/realsense_samples/blob/master/README.md for more information on required steps for building the samples, including installing the SLAM, Person, and Object middleware. The headers and libraries for these libraries are included in the librealsense-object-recognition-dev, librealsense-persontracking-dev, and librealsense-slam-dev packages, and have now been released.

**Comment by yunchancho** [comment]
Hi @mattcurfman. 
Thank you for your anouncement! I and my company are waiting this release, since we are preparing digital signage devices with realsense in South Korea. By now, we are developing them using our in-house vision solution regarding person/object detection. It was not easy to detect them more accurately. 

I will test your person/object libraries as possible as I can do, and let you know here if any problem occurs. 
Thansks for your support again.
