### ISSUE TITLE
Missing or_data_interface.h

### ISSUE THREAD

**Issue by broody** [IntelRealSense/realsense_samples#2]
Hello,

When I tried building these samples I get the error below. I have both librealsense and realsense sdk installed, am I missing something else?

/home/broody/realsense_samples/samples/or_pt_tutorial_1/../common/utils/pt_utils.hpp:10:31: fatal error: or_data_interface.h: No such file or directory
compilation terminated.

**Comment by mattcurfman** [comment]
Hi, please see "Building The Samples" in the README.md @ https://github.com/IntelRealSense/realsense_samples/blob/master/README.md for more information on required steps for building the samples, including installing the SLAM, Person, and Object middleware.  The headers and libraries for these libraries are included in the librealsense-object-recognition-dev, librealsense-persontracking-dev, and librealsense-slam-dev packages.

**Comment by broody** [comment]
Thanks! Is it possible these examples be made available as Yocto recipe as well?

**Comment by mattcurfman** [comment]
@broody There are not currently any plans to provide these for Yocto.
