### ISSUE TITLE
Missing person_tracking_video_module_factory.h

### ISSUE THREAD

**Issue by VMakhitko** [IntelRealSense/realsense_samples#3]
Hello,

When I tried building samples according to instruction https://software.intel.com/sites/products/realsense/intro/getting_started.html.

I have got the error:
realsense_samples/samples/or_tutorial_1_gui/../common/utils/pt_utils.hpp:13:50: fatal error: person_tracking_video_module_factory.h: No such file or directory

**Comment by mattcurfman** [comment]
Can you verify that you've installed the development packages for RealSense?  
```bash
sudo apt install librealsense-object-recognition-dev librealsense-persontracking-dev librealsense-slam-dev
```

This error usually indicates the missing development packages.

**Comment by VMakhitko** [comment]
I just double checked. All packages installed.

And also I checked /usr directory. 
This header present by path
/usr/include/librealsense/pt/person_tracking_video_module_factory.h

But cmake doesn't see it.

**Comment by VMakhitko** [comment]
I found the issue. 
I add "/usr/include/librealsense/pt" string to include_directories into CMakeLists.txt
fot or_tutorial_1_gui example.
