### ISSUE TITLE
Is it possible to use the R200 camera?

### ISSUE THREAD

**Issue by antoan** [IntelRealSense/realsense_samples#4]
I would very much like to try the SLAM sample with my R200 sensor, is this possible in principle? The developer guide below, only refers to the ZR300 camera.
https://software.intel.com/sites/products/realsense/slam/developer_guide.html

**Comment by mattcurfman** [comment]
The ZR300 camera is derived from the R200 camera, but has an additional wide-angle 'fisheye' camera, a high accuracy IMU, and a micro controller that timestamps all of the camera shutters and IMU data together.  The SLAM sample requires these additional capabilities to run, and is why the SLAM sample does not support the R200 camera.  Hope this helps clarify

**Comment by antoan** [comment]
Much appreciated.
